//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Resources.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ChallengesController_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChallengesController_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FitAppServerREST.Resources.Controllers.ChallengesController.en", typeof(ChallengesController_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bench: 2023.
        /// </summary>
        internal static string benchTotalWeight2023 {
            get {
                return ResourceManager.GetString("benchTotalWeight2023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In 2023, bench a total weight of 100k kg.
        /// </summary>
        internal static string benchTotalWeight2023Description {
            get {
                return ResourceManager.GetString("benchTotalWeight2023Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become a Gym Bro.
        /// </summary>
        internal static string benchTwoPlatesChallenge {
            get {
                return ResourceManager.GetString("benchTwoPlatesChallenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bench press two plates on each side.
        /// </summary>
        internal static string benchTwoPlatesChallengeDescription {
            get {
                return ResourceManager.GetString("benchTwoPlatesChallengeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big boy deadlift.
        /// </summary>
        internal static string deadliftThreePlatesChallenge {
            get {
                return ResourceManager.GetString("deadliftThreePlatesChallenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadlift three plates on each side.
        /// </summary>
        internal static string deadliftThreePlatesChallengeDescription {
            get {
                return ResourceManager.GetString("deadliftThreePlatesChallengeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certified forklift.
        /// </summary>
        internal static string deadliftTotalWeight2023 {
            get {
                return ResourceManager.GetString("deadliftTotalWeight2023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In 2023, deadlift a total weight of 300k kg.
        /// </summary>
        internal static string deadliftTotalWeight2023Description {
            get {
                return ResourceManager.GetString("deadliftTotalWeight2023Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting there.
        /// </summary>
        internal static string deadliftTwoPlatesChallenge {
            get {
                return ResourceManager.GetString("deadliftTwoPlatesChallenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadlift two plates on each side.
        /// </summary>
        internal static string deadliftTwoPlatesChallengeDescription {
            get {
                return ResourceManager.GetString("deadliftTwoPlatesChallengeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pullups: 2023.
        /// </summary>
        internal static string numberOfPullups2023 {
            get {
                return ResourceManager.GetString("numberOfPullups2023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In 2023, do 10,000 pullups.
        /// </summary>
        internal static string numberOfPullups2023Description {
            get {
                return ResourceManager.GetString("numberOfPullups2023Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workouts: 2023.
        /// </summary>
        internal static string numOfCreatedWorkoutsChallenge2023 {
            get {
                return ResourceManager.GetString("numOfCreatedWorkoutsChallenge2023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In 2023, go to the gym 200 times.
        /// </summary>
        internal static string numOfCreatedWorkoutsChallenge2023Description {
            get {
                return ResourceManager.GetString("numOfCreatedWorkoutsChallenge2023Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On top of the world.
        /// </summary>
        internal static string ohpOnePlateChallenge {
            get {
                return ResourceManager.GetString("ohpOnePlateChallenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OHP one plate on each side.
        /// </summary>
        internal static string ohpOnePlateChallengeDescription {
            get {
                return ResourceManager.GetString("ohpOnePlateChallengeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OHP: 2023.
        /// </summary>
        internal static string ohpTotalWeight2023 {
            get {
                return ResourceManager.GetString("ohpTotalWeight2023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In 2023, OHP a total weight of 50k kg.
        /// </summary>
        internal static string ohpTotalWeight2023Description {
            get {
                return ResourceManager.GetString("ohpTotalWeight2023Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squat: 2023.
        /// </summary>
        internal static string squatTotalWeight2023 {
            get {
                return ResourceManager.GetString("squatTotalWeight2023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In 2023, squat a total weight of 200k kg.
        /// </summary>
        internal static string squatTotalWeight2023Description {
            get {
                return ResourceManager.GetString("squatTotalWeight2023Description", resourceCulture);
            }
        }
    }
}
