name: Deploy to dev2
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ dev2 ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      DOCKER_TAG : ${{ github.run_id }}-${{ github.run_attempt }}
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            # Change to variable
            cd /srv/backend/FitAppServer
            git pull
            docker build -f ./FitAppServerREST/Dockerfile . -t fitapp-server:${{ env.DOCKER_TAG }}
